### ISSUE TITLE
Get user access token method

### ISSUE THREAD

**Issue by danielckv** [AnderGoig/SwiftInstagram#14]
## Checklist

- [x] I've the [latest update](https://github.com/AnderGoig/SwiftInstagram/releases) of Swiftinstagram.
- [x] I've searched for [existing GitHub issues](https://github.com/AnderGoig/SwiftInstagram/issues).
- [x] I've read the [wiki pages](https://github.com/AnderGoig/SwiftInstagram/wiki).
- [x] I've read the [contibution guidelines](CONTRIBUTING.md).

## Expected Behavior

I'm looking for a method where I can receive user's access token, looks like there is something but it's available privately. Any reasons why?

**Comment by AnderGoig** [comment]
Hi @danielckv, the only reason is that, at first, I just thought that nobody would use it. But it seems I was wrong 😌. Anyway, thanks for your contribution!
