### ISSUE TITLE
Getting list of follows or followers by user ID 

### ISSUE THREAD

**Issue by TaoufikBouabid** [AnderGoig/SwiftInstagram#16]
## Checklist

- [-] I've the [latest update](https://github.com/AnderGoig/SwiftInstagram/releases) of Swiftinstagram.
- [-] I've searched for [existing GitHub issues](https://github.com/AnderGoig/SwiftInstagram/issues).
- [-] I've read the [wiki pages](https://github.com/AnderGoig/SwiftInstagram/wiki).
- [-] I've read the [contibution guidelines](CONTRIBUTING.md).

## Expected Behavior
Is it possible to get list of followers or follows by userID not self only ? 
p.s : I'm still in sandbox mode

## Actual Behavior
The actual is get list of my followers and follows

## Specifications

  - **iOS Version**: 11.2
  - **Device(s)**: iphone 6s plus

**Comment by AnderGoig** [comment]
Hi @TaoufikBouabid, unfortunately the Instagram API doesn't provide that, you could only get the number of followers and follows, but not the list of them.

**Comment by TaoufikBouabid** [comment]
is there any workaround ?

**Comment by AnderGoig** [comment]
Not that I know, sorry.
