### ISSUE TITLE
Invalid Media ID

### ISSUE THREAD

**Issue by black-lotus** [AnderGoig/SwiftInstagram#21]
## Checklist

- [ ] I've the [latest update](https://github.com/AnderGoig/SwiftInstagram/releases) of Swiftinstagram.
- [ ] I've searched for [existing GitHub issues](https://github.com/AnderGoig/SwiftInstagram/issues).
- [ ] I've read the [wiki pages](https://github.com/AnderGoig/SwiftInstagram/wiki).
- [ ] I've read the [contibution guidelines](CONTRIBUTING.md).

## Expected Behavior
I should get Media data as Instagram Documentation like this [Instagram media](https://www.instagram.com/developer/endpoints/media/)

## Actual Behavior
I have already Authentication then get media data
Auth -> Fetch Data (Media)
but i got an error like this 
`[invalidRequest] - invalid media id`

## Steps to Reproduce the Problem

  1. Auth
  2. Fetch with this shortcode Ba6NSWUFLfj

## Specifications

  - **iOS Version**: iOS 100
  - **Device(s)**: Simulator iPhone 8 Plus

**Comment by AnderGoig** [comment]
Hi @black-lotus, there are two methods to fetch a media object:

`media(id: <your media id>, ...)` and `media(shortcode: <your media shortcode>, ...)`

Which one are you using?

**Comment by black-lotus** [comment]
I am using shortcode since i have only shortcode url
`media(shortcode: <your media shortcode>, ...)`

**Comment by AnderGoig** [comment]
Hi @black-lotus, sorry for the late response. I've been testing it and I found something interesting. It seems that when you are in sandbox mode, the data that Instagram API handles is restricted to the 20 most recent media. Also the media must be from users inside the sandbox. I've tried with this conditions and works. 

Hope it helps you! 🤞
