### ISSUE TITLE
Instagram authentication not working properly

### ISSUE THREAD

**Issue by elementsrtyte** [AnderGoig/SwiftInstagram#23]
## Checklist

- [ x] I've the [latest update](https://github.com/AnderGoig/SwiftInstagram/releases) of Swiftinstagram.
- [ x] I've searched for [existing GitHub issues](https://github.com/AnderGoig/SwiftInstagram/issues).
- [x ] I've read the [wiki pages](https://github.com/AnderGoig/SwiftInstagram/wiki).
- [x ] I've read the [contibution guidelines](CONTRIBUTING.md).

## Expected Behavior
When I am prompted the instagram login screen, and I push 'Log in', the success or failure callback should be triggered.

## Actual Behavior
When I am prompted the instagram login screen, and i push 'Log in', I am routed to a Instagram branded, 'page not found' page.  None of the callbacks are called and I don't receive an access token.

I inspected the traffic and it looks like the following POST call is resulting in a 404, regardless whether the username or password is correct:
https://www.instagram.com/accounts/login/?force_classic_login=&next=/oauth/authorize%3Fclient_id%CLIENT_ID%26redirect_uri%3DREDIRECT_URI%26response_type%3Dtoken%26scope%3Dbasic

I think the issue may be around this.

## Steps to Reproduce the Problem
1. Ensure user is logged out.  Just call this method to bring up the instagram login screen.  
```
Instagram.shared.login(from: self.navigationController!, success: {
                    print("Success")
                }, failure: { error in
                    print(error.localizedDescription)
                })
```
## Specifications

  - **iOS Version**: 11.2
  - **Device(s)**: iPhone 7

**Comment by antoniqhc** [comment]
Same one

**Comment by LeandroIvan** [comment]
Did you guys put the right InstagramRedirectURI and InstagramClientID inside the Info.plist file?

**Comment by AnderGoig** [comment]
I've trying to reproduce your problem but I can't, have you tried again? Maybe it was a temporary error.

**Comment by elementsrtyte** [comment]
Yep, it was on the instagram side.  Looks like it's working fine now.  Thanks for checking.

**Comment by KingOlami** [comment]
how do I get InstagramRedirectURI?
