### ISSUE TITLE
pod 'SwiftInstagram', '~> 1.1.0' not working

### ISSUE THREAD

**Issue by ryandailey100** [AnderGoig/SwiftInstagram#24]
When I run a pod install, I get the following error:

[!] Unable to satisfy the following requirements:

- `SwiftInstagram (~> 1.1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SwiftInstagram (~> 1.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

PS: I have many other pods that were successfully able to install, this is the only one that I am having trouble with.

**Comment by AnderGoig** [comment]
Have you tried with `pod install --repo-update`?

**Comment by ryandailey100** [comment]
Perfect that did the trick, thanks! 👍
