### ISSUE TITLE
authentication not working

### ISSUE THREAD

**Issue by daiwud** [AnderGoig/SwiftInstagram#25]
let igLoginManager = Instagram.shared
igLoginManager.login(from: vc, success: {
 // not callback (success)
}) { (error) in
 // not callback (error)
}

I do not get any answers.
Disable implicit OAuth: uncheck
InstagramClientId: my details
InstagramRedirectURI: my details

I get successfully to my page and do not get any response. Please tell me what could be wrong

**Comment by AnderGoig** [comment]
I feel this is the same as #23, I've just tried to log in and I haven't had any problem. Could you try it again?

**Comment by daiwud** [comment]
As far as I understood the problems were on the side of the instagram, since I already have no problems either. Thank you.

**Comment by AnderGoig** [comment]
Yep, thanks, closing this one.
