### ISSUE TITLE
SwiftInstagram.InstagramError error 0

### ISSUE THREAD

**Issue by ryandailey100** [AnderGoig/SwiftInstagram#26]
As of today, I keep getting this error message when I call recentMedia(fromUser: "self"....
This error was non-existent up until today. Here's what gets printed in the console:

The operation couldn’t be completed. (SwiftInstagram.InstagramError error 0.)

I am still able to login and logout. This error only occurs when I call api.recentMedia(fromUser: "self"....

Another thing to note is that when I enter this link in my web browser "https://api.instagram.com/v1/users/self/media/recent?access_token=MYTOKEN", I am able to get a response from Instagram, which proves it is not a problem on Instagrams end. It is possible that they have slightly changed the response as of today, which might be causing problems with this api, but I am not too sure about that.  

UPDATE: After digging in further, I have located where the error occurs. Still not sure why it throws an error. After running line 139 (refer to the image below), the app then catches an error and then runs line 156. Please help me fix this problem, thanks!

<img width="837" alt="screen shot 2018-04-06 at 1 18 31 am" src="https://user-images.githubusercontent.com/15038444/38404516-a9814f2a-3938-11e8-829e-b4036d11ebf1.png">

**Comment by AnderGoig** [comment]
Would you be able to print the error on line 156? Just like this:
```swift
print(error)
```

**Comment by ryandailey100** [comment]
Here is what gets printed:

<img width="356" alt="screen shot 2018-04-06 at 12 04 43 pm" src="https://user-images.githubusercontent.com/15038444/38431627-d5036688-3992-11e8-8056-9abd98f73f78.png">

**Comment by AnderGoig** [comment]
Thanks @ryandailey100, I've found the error. There was a problem decoding media with tagged users in the picture. An update will be released ASAP.

**Comment by ryandailey100** [comment]
Thanks so much! Appreciate the quick bug fix 👍
