### ISSUE TITLE
 Value of type 'JSONDecoder' has no member 'keyDecodingStrategy'

### ISSUE THREAD

**Issue by ranhsd** [AnderGoig/SwiftInstagram#29]
Hi, I am getting this error after upgrading to the latest version (1.1.1) via cocoapods.

<img width="439" alt="screen shot 2018-04-09 at 22 14 49" src="https://user-images.githubusercontent.com/3685671/38517758-a4897f3e-3c43-11e8-95a4-8a7caa51f744.png">

I read about it a bit and it looks like a known bug in Swift

https://bugs.swift.org/browse/SR-7180

The problem is that the in older version (1.1.0) I cannot fetch the user media so that's the reason why I upgrade it to the latest one.

**Comment by KhashayarJan** [comment]
That's not a bug.
keyDecodingStrategy is part of Swift 4.1 which is included in Xcode 9.3
update your Xcode and the error will go away
