### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by thedoubler** [AnderGoig/SwiftInstagram#35]
## Checklist

- [x] I've the [latest update](https://github.com/AnderGoig/SwiftInstagram/releases) of Swiftinstagram.
- [x] I've searched for [existing GitHub issues](https://github.com/AnderGoig/SwiftInstagram/issues).
- [x] I've read the [wiki pages](https://github.com/AnderGoig/SwiftInstagram/wiki).
- [x] I've read the [contibution guidelines](CONTRIBUTING.md).

## Expected Behavior

Should login succesfully.

## Actual Behavior

Not login succesfully. Received an Error in webview.
<img width="368" alt="screen shot 2018-05-25 at 17 54 11" src="https://user-images.githubusercontent.com/11870889/40554091-5112cc2e-604d-11e8-82fa-192d239a3d18.png"> (see attached screenshot)

## Steps to Reproduce the Problem

  1. Added pod to Podfile and install
  2. Added to Info.plist keys from 'SwiftInstagram authentication' section
  3. Added sample code for login

## Specifications

  - **iOS Version**: 11.0
  - **Device(s)**: Simulator / iPhone 6

**Comment by AdrienBre** [comment]
yes, I have the exact same problem.

**Comment by nikolajholck** [comment]
I have the same issue with my custom Instagram integration. Perhaps it's an Instagram API issue?

**Comment by andermoran** [comment]
Does it work now? It works fine for me.

**Comment by AdrienBre** [comment]
Yes it works now, I think it was an Instagram API thing for Europe because of this new laws etc... it looks ok now.
