### ISSUE TITLE
Example Project does not log in successfully

### ISSUE THREAD

**Issue by n13** [AnderGoig/SwiftInstagram#42]
## Checklist

- [x] I've the [latest update](https://github.com/AnderGoig/SwiftInstagram/releases) of Swiftinstagram.
- [x] I've searched for [existing GitHub issues](https://github.com/AnderGoig/SwiftInstagram/issues).
- [x] I've read the [wiki pages](https://github.com/AnderGoig/SwiftInstagram/wiki).
- [x] I've read the [contibution guidelines](CONTRIBUTING.md).

## Expected Behavior
Clicking the login button, the example project logs in

## Actual Behavior
After entering all my data into instagram, the view controller returned with an error message

## Steps to Reproduce the Problem

  1. Run example app InstagramLogin-Example
  1. Try to log in

## Specifications

  - **iOS Version**:
iOS 11.4
  - **Device(s)**:
Simulator - iPhone 6s

<img width="373" alt="image" src="https://user-images.githubusercontent.com/65412/42145070-80325ddc-7df1-11e8-91d4-30a8a3a5b1f9.png">

**Comment by AnderGoig** [comment]
Thanks @n13, but this is not the correct repository for this issue, please open it on https://github.com/AnderGoig/InstagramLogin.

**Comment by n13** [comment]
Umm... ok... why is it not the right place to replort? I used this repo? Or is this outdated?

Anyway in the meantime I wrote my own solution to this so nevermind ;)
