### ISSUE TITLE
Error 1- "This endpoint has been retired" error?

### ISSUE THREAD

**Issue by yildirimatcioglu** [AnderGoig/SwiftInstagram#45]
## Checklist

- [x] I've the [latest update](https://github.com/AnderGoig/SwiftInstagram/releases) of Swiftinstagram.
- [ ] I've searched for [existing GitHub issues](https://github.com/AnderGoig/SwiftInstagram/issues).
- [ ] I've read the [wiki pages](https://github.com/AnderGoig/SwiftInstagram/wiki).
- [ ] I've read the [contibution guidelines](CONTRIBUTING.md).

## Expected Behavior
retrieve follower list data

## Actual Behavior

retrieving Error 1- "This endpoint has been retired" error
## Steps to Reproduce the Problem

  1.When retrieving the followerlist data this gave me response gave me this error.
  2. I think instagram change endpoints so this framework should be update.
 

## Specifications

  - **iOS Version**:
  - **Device(s)**:

**Comment by AnderGoig** [comment]
Hi @wixvii, unfortunately, Instagram deprecated some of the API endpoints in April, including the one to retrieve the list of followers (https://www.instagram.com/developer/changelog/). There's nothing I can do about it. I will update the documentation to let everybody know.
