### ISSUE TITLE
Cocoapods bug

### ISSUE THREAD

**Issue by MarcoCarnevali** [AnderGoig/SwiftInstagram#9]
Hello, I can't install the library with cocoa pods:
```
pod install
Analyzing dependencies
[!] Unable to find a specification for `SwiftInstagram (~> 1.0.4)`
```

**Comment by AnderGoig** [comment]
Hi @MarcoCarnevali,

It seems that your local Cocoapods repo is outdated. Try to run the following command and then try again:

`pod repo update`
